version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    command:
      - /bin/bash
      - -c
      - |
        # Wait for Zookeeper and Kafka to fully start
        sleep 20;
        # Start Kafka server in the background
        /etc/confluent/docker/run &
        # Create the topic after Kafka is running
        kafka-topics --create --topic event-topic --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1;
        # Keep the container running
        tail -f /dev/null

  flink-jobmanager:
    image: flink:1.17
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
    volumes:
      - ./flink-kafka-integration/target:/opt/flink/jars
    depends_on:
      - kafka

  flink-taskmanager:
    image: flink:1.17
    container_name: flink-taskmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
    depends_on:
      - flink-jobmanager
